name: Deploy to Cloudflare Workers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install latest Wrangler
      run: |
        npm uninstall -g @cloudflare/wrangler  # 卸载老版
        npm install -g wrangler  # 装最新版（现在直接叫wrangler）
        npm link wrangler  # 确保链接
        echo "$(npm bin -g)" >> $GITHUB_PATH  # 更新PATH

    - name: Verify Wrangler installation
      run: wrangler --version  # 确认版本（应该看到3.x.x）

    - name: Replace KV_NAME in wrangler.toml
      run: sed -i "s/KV_NAME/${{ secrets.KV_NAME }}/g" wrangler.toml

    - name: Deploy to Cloudflare
      run: wrangler deploy  # 新版用法，不用--api-token和--account-id，直接用Secrets配置
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # 新版用这个环境变量
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}  # 新版用这个环境变量
